services:
  frontend:
    build: .
    command: [nginx, '-g', 'daemon off;']
    volumes:
      - ./build/web:/usr/share/nginx/html
      - ./assets/certs:/etc/nginx/certs
    ports:
      - "80:80"
      - "443:443"
    stdin_open: true
    tty: true
